apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimic.fullname" . }}-config
  labels:
    {{- include "mimic.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "mimic.config" . | nindent 4 }}