apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimic.fullname" . }}
  labels:
    {{- include "mimic.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
      name: {{ .Values.service.http.name }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.targetPort }}
      protocol: TCP
      name: {{ .Values.service.grpc.name }}
  selector:
    {{- include "mimic.selectorLabels" . | nindent 4 }}